version: "20.10"
services:
    DataBasePg:
        container_name: dbpg
        image: postgres:13
        environment:
          - POSTGRES_DB=test
          - POSTGRES_USER=admin
          - POSTGRES_PASSWORD=admin
        ports:
          - 5678:5432
    DataBaseOracle:
        container_name: dbora
        image: wnameless/oracle-xe-11g-r2
        environment:
          - ORACLE_ENABLE_XDB=true
        ports:
          - 49161:1521

    DatabaseSqlServer:
        container_name: dbmssql
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
          - ACCEPT_EULA=Y
          - MSSQL_SA_PASSWORD=12345678Pa@
          - MSSQL_PID=Express
        ports:
          - 1437:1433

    DatabaseMySql:
        container_name: dbmysql
        image: mysql:8.0.30
        environment:
          - MYSQL_ROOT_PASSWORD=12345
        ports:
          - 3308:3306
        volumes:
          - mysql_db_data_container:/var/lib/mysql          
volumes:
  mysql_db_data_container: